---
title: classifier
toc-depth: 3
toc-expand: 3
---

Test suites for sklearn-compatible classifier models Ideal setup is to have the API client to read a custom test suite from the project's configuration

### [class]{.muted} TabularDataQuality

```python
class TabularDataQuality({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for data quality on tabular datasets

**Inherited members**

**Methods**

### [class]{.muted} TabularDatasetDescription

```python
class TabularDatasetDescription({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite to extract metadata and descriptive statistics from a tabular dataset

**Inherited members**

**Methods**

### [class]{.muted} ClassifierDiagnosis

```python
class ClassifierDiagnosis({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for sklearn classifier model diagnosis tests

**Inherited members**

**Methods**

### [class]{.muted} ClassifierFullSuite

```python
class ClassifierFullSuite({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Full test suite for binary classification models.

**Inherited members**

**Methods**

### [class]{.muted} ClassifierMetrics

```python
class ClassifierMetrics({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for sklearn classifier metrics

**Inherited members**

**Methods**

### [class]{.muted} ClassifierModelValidation

```python
class ClassifierModelValidation({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for binary classification models.

**Inherited members**

**Methods**

### [class]{.muted} ClassifierPerformance

```python
class ClassifierPerformance({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for sklearn classifier models

**Inherited members**

**Methods**
