---
title: test_suites
toc-depth: 3
toc-expand: 3
---

Entrypoint for test suites.

- [classifier](test_suites/classifier.qmd)
- [cluster](test_suites/cluster.qmd)
- [embeddings](test_suites/embeddings.qmd)
- [llm](test_suites/llm.qmd)
- [nlp](test_suites/nlp.qmd)
- [parameters_optimization](test_suites/parameters_optimization.qmd)
- [regression](test_suites/regression.qmd)
- [statsmodels_timeseries](test_suites/statsmodels_timeseries.qmd)
- [summarization](test_suites/summarization.qmd)
- [tabular_datasets](test_suites/tabular_datasets.qmd)
- [text_data](test_suites/text_data.qmd)
- [time_series](test_suites/time_series.qmd)

### [class]{.muted} ClassifierDiagnosis

```python
class ClassifierDiagnosis({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for sklearn classifier model diagnosis tests

**Inherited members**

**Methods**

### [class]{.muted} ClassifierFullSuite

```python
class ClassifierFullSuite({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Full test suite for binary classification models.

**Inherited members**

**Methods**

### [class]{.muted} ClassifierMetrics

```python
class ClassifierMetrics({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for sklearn classifier metrics

**Inherited members**

**Methods**

### [class]{.muted} ClassifierModelValidation

```python
class ClassifierModelValidation({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for binary classification models.

**Inherited members**

**Methods**

### [class]{.muted} ClassifierPerformance

```python
class ClassifierPerformance({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for sklearn classifier models

**Inherited members**

**Methods**

### [class]{.muted} ClusterFullSuite

```python
class ClusterFullSuite({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Full test suite for clustering models.

**Inherited members**

**Methods**

### [class]{.muted} ClusterMetrics

```python
class ClusterMetrics({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for sklearn clustering metrics

**Inherited members**

**Methods**

### [class]{.muted} ClusterPerformance

```python
class ClusterPerformance({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for sklearn cluster performance

**Inherited members**

**Methods**

### [class]{.muted} EmbeddingsFullSuite

```python
class EmbeddingsFullSuite({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Full test suite for embeddings models.

**Inherited members**

**Methods**

### [class]{.muted} EmbeddingsMetrics

```python
class EmbeddingsMetrics({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for embeddings metrics

**Inherited members**

**Methods**

### [class]{.muted} EmbeddingsPerformance

```python
class EmbeddingsPerformance({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for embeddings model performance

**Inherited members**

**Methods**

### [class]{.muted} KmeansParametersOptimization

```python
class KmeansParametersOptimization({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for sklearn hyperparameters optimization

**Inherited members**

**Methods**

### [class]{.muted} LLMClassifierFullSuite

```python
class LLMClassifierFullSuite({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Full test suite for LLM classification models.

**Inherited members**

**Methods**

### [class]{.muted} NLPClassifierFullSuite

```python
class NLPClassifierFullSuite({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Full test suite for NLP classification models.

**Inherited members**

**Methods**

### [class]{.muted} PromptValidation

```python
class PromptValidation({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for prompt validation

**Inherited members**

**Methods**

### [class]{.muted} RegressionFullSuite

```python
class RegressionFullSuite({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Full test suite for regression models.

**Inherited members**

**Methods**

### [class]{.muted} RegressionMetrics

```python
class RegressionMetrics({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for performance metrics of regression metrics

**Inherited members**

**Methods**

### [class]{.muted} RegressionModelDescription

```python
class RegressionModelDescription({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for performance metric of regression model of statsmodels library

**Inherited members**

**Methods**

### [class]{.muted} RegressionModelsEvaluation

```python
class RegressionModelsEvaluation({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for metrics comparison of regression model of statsmodels library

**Inherited members**

**Methods**

### [class]{.muted} RegressionPerformance

```python
class RegressionPerformance({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for regression model performance

**Inherited members**

**Methods**

### [class]{.muted} SummarizationMetrics

```python
class SummarizationMetrics({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for Summarization metrics

**Inherited members**

**Methods**

### [class]{.muted} TabularDataQuality

```python
class TabularDataQuality({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for data quality on tabular datasets

**Inherited members**

**Methods**

### [class]{.muted} TabularDataset

```python
class TabularDataset({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for tabular datasets.

**Inherited members**

**Methods**

### [class]{.muted} TabularDatasetDescription

```python
class TabularDatasetDescription({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite to extract metadata and descriptive statistics from a tabular dataset

**Inherited members**

**Methods**

### [class]{.muted} TextDataQuality

```python
class TextDataQuality({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for data quality on text data

**Inherited members**

**Methods**

### [class]{.muted} TimeSeriesDataQuality

```python
class TimeSeriesDataQuality({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for data quality on time series datasets

**Inherited members**

**Methods**

### [class]{.muted} TimeSeriesDataset

```python
class TimeSeriesDataset({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for time series datasets.

**Inherited members**

**Methods**

### [class]{.muted} TimeSeriesModelValidation

```python
class TimeSeriesModelValidation({'cls': 'ExprName', 'name': 'TestSuite'}):
```

Test suite for time series model validation.

**Inherited members**

**Methods**

### [class]{.muted} TimeSeriesMultivariate

```python
class TimeSeriesMultivariate({'cls': 'ExprName', 'name': 'TestSuite'}):
```

This test suite provides a preliminary understanding of the features and relationship in multivariate dataset. It presents various multivariate visualizations that can help identify patterns, trends, and relationships between pairs of variables. The visualizations are designed to explore the relationships between multiple features simultaneously. They allow you to quickly identify any patterns or trends in the data, as well as any potential outliers or anomalies. The individual feature distribution can also be explored to provide insight into the range and frequency of values observed in the data. This multivariate analysis test suite aims to provide an overview of the data structure and guide further exploration and modeling.

**Inherited members**

**Methods**

### [class]{.muted} TimeSeriesUnivariate

```python
class TimeSeriesUnivariate({'cls': 'ExprName', 'name': 'TestSuite'}):
```

This test suite provides a preliminary understanding of the target variable(s) used in the time series dataset. It visualizations that present the raw time series data and a histogram of the target variable(s).

The raw time series data provides a visual inspection of the target variable's behavior over time. This helps to identify any patterns or trends in the data, as well as any potential outliers or anomalies. The histogram of the target variable displays the distribution of values, providing insight into the range and frequency of values observed in the data.

**Inherited members**

**Methods**

## describe_suite[()]{.muted}

```python
def describe_suite(
    test_suite_id: str,
    verbose = False):
```

Describes a Test Suite by ID

**Parameters**

- **test_suite_id**: Test Suite ID
- **verbose**: If True, describe all plans and tests in the Test Suite

**Returns**

- A formatted table with the Test Suite description

## get_by_id[()]{.muted}

```python
def get_by_id(
    test_suite_id: str):
```

Returns the test suite by ID

## list_suites[()]{.muted}

```python
def list_suites(
    pretty: bool = True):
```

Returns a list of all available test suites

## register_test_suite[()]{.muted}

```python
def register_test_suite(
    suite_id: str,
    suite: TestSuite):
```

Registers a custom test suite
