---
title: "[validmind](/reference/validmind.html).taiwan_credit"
sidebar: validmind-reference
toc-depth: 4
toc-expand: 4
---

## simple_preprocess_booleans<span class='muted'>()</span>

<!-- function.qmd.jinja2 - function signature -->

::: {.signature}

<span class="signature">
<span class="kw">def</span> <span class="name">simple_preprocess_booleans</span>(
    <span class="param"><span class="n">df</span></span>,    <span class="param"><span class="n">columns</span></span>):</span>
</span>

:::

Preprocess boolean columns.

**Parameters**

- **df** pandas.DataFrame: Dataframe to preprocess.
- **columns** list: List of columns to preprocess.

**Returns**

- Preprocessed dataframe.

## simple_preprocess_categoricals<span class='muted'>()</span>

<!-- function.qmd.jinja2 - function signature -->

::: {.signature}

<span class="signature">
<span class="kw">def</span> <span class="name">simple_preprocess_categoricals</span>(
    <span class="param"><span class="n">df</span></span>,    <span class="param"><span class="n">columns</span></span>):</span>
</span>

:::

Preprocess categorical columns.

**Parameters**

- **df** pandas.DataFrame: Dataframe to preprocess.
- **columns** list: List of columns to preprocess.

**Returns**

- Preprocessed dataframe.

## simple_preprocess_numericals<span class='muted'>()</span>

<!-- function.qmd.jinja2 - function signature -->

::: {.signature}

<span class="signature">
<span class="kw">def</span> <span class="name">simple_preprocess_numericals</span>(
    <span class="param"><span class="n">df</span></span>,    <span class="param"><span class="n">columns</span></span>):</span>
</span>

:::

Preprocess numerical columns.

**Parameters**

- **df** pandas.DataFrame: Dataframe to preprocess.
- **columns** list: List of columns to preprocess.

**Returns**

- Preprocessed dataframe.

## load_data[()]{.muted}

<!-- function.qmd.jinja2 - function signature -->

::: {.signature}

<span class="signature">
<span class="kw">def</span> <span class="name">load_data</span>(<span class="param"><span class="n"></span></span>):</span>
</span>

:::

## preprocess[()]{.muted}

<!-- function.qmd.jinja2 - function signature -->

::: {.signature}

<span class="signature">
<span class="kw">def</span> <span class="name">preprocess</span>(<span class="param"><span class="n">df</span></span>):</span>
</span>

:::
