from pathlib import Path

FILE_PATH = Path("validmind/tests/__types__.py")
COPYRIGHT_PATH = Path("scripts/copyright.txt")

from validmind.tests import list_tests

test_ids = list_tests(pretty=False)

tests_str = "\n".join([f'        "{test_id}",' for test_id in test_ids])
tests_str = tests_str.rstrip("\n")

copyright_header = COPYRIGHT_PATH.read_text().strip()

source = f'''{copyright_header}

"""Literal types for test IDs.

This module is auto-generated by running `make generate-test-id-types`.
Should not be modified manually.
"""

from typing import Literal, Union

TestID = Union[
    Literal[
{tests_str}
    ],
    str,
]
'''

if not FILE_PATH.exists() or FILE_PATH.read_text() != source:
    FILE_PATH.write_text(source)

print(f"Generated test ID literals and saved in {FILE_PATH}")
