FILE_PATH = "validmind/tests/__types__.py"

# in case something is wrong with the existing __types__.py file, set to empty before running rest of script
empty_src = """
from typing import Literal, Union

TestID = Union[Literal["test_id"], str]
"""

with open(FILE_PATH, "w") as f:
    f.write(empty_src)

from validmind.tests import list_tests

test_ids = list_tests(pretty=False)

tests_str = "\n".join([f'        "{test_id}",' for test_id in test_ids])
tests_str = tests_str.rstrip("\n")

source = f'''# Copyright © 2023-2024 ValidMind Inc. All rights reserved.
# See the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial

"""Literal types for test IDs.

This module is auto-generated by running `make generate-test-id-types`.
Should not be modified manually.
"""

from typing import Literal, Union

TestID = Union[
    Literal[
{tests_str}
    ],
    str,
]
'''

with open(FILE_PATH, "w") as f:
    f.write(source)

print(f"Generated test ID literals and saved in {FILE_PATH}")
