# This workflow will install Python dependencies and generate
# Quarto documentation using Griffe for API extraction and
# Jinja2 templates for the docs and navigation.
name: Python Library API docs for Quarto

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  workflow_dispatch:
    inputs:
      note:
        description: "Provide a description of the changes"
        required: true
        default: "Update quarto docs"

permissions:
  contents: write

jobs:
  quarto-docs:
    runs-on:
      group: ubuntu-vm-large

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use python3.11
          poetry install -E huggingface -E llm
          poetry run pip install torch==2.0.1 --extra-index-url https://download.pytorch.org/whl/cpu
          poetry run pip install aequitas fairlearn vl-convert-python
          poetry run pip install griffe mdformat docstring_parser

      - name: Generate Quarto Docs
        run: make quarto-docs

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Generate quarto docs"
          title: "Generate quarto docs"
          body: |
            Auto-generated PR to update Quarto documentation.
            
            ${{ github.event.inputs.note || 'Triggered by push to main' }}
          branch: quarto-docs-update
          delete-branch: true
          add-paths: |
            docs/

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
